# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class Event(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Level(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Event.Level': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Event.Level']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Event.Level']]: ...
        VERBOSE = typing___cast('Event.Level', 0)
        DEBUG = typing___cast('Event.Level', 1)
        INFORMATION = typing___cast('Event.Level', 2)
        WARNING = typing___cast('Event.Level', 3)
        ERROR = typing___cast('Event.Level', 4)
        FAILURE = typing___cast('Event.Level', 5)
    VERBOSE = typing___cast('Event.Level', 0)
    DEBUG = typing___cast('Event.Level', 1)
    INFORMATION = typing___cast('Event.Level', 2)
    WARNING = typing___cast('Event.Level', 3)
    ERROR = typing___cast('Event.Level', 4)
    FAILURE = typing___cast('Event.Level', 5)

    level = ... # type: Event.Level
    code = ... # type: builtin___int
    scope = ... # type: typing___Text
    description = ... # type: typing___Text

    def __init__(self,
        *,
        level : typing___Optional[Event.Level] = None,
        code : typing___Optional[builtin___int] = None,
        scope : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Event: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"code",u"description",u"level",u"scope"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"code",b"code",u"description",b"description",u"level",b"level",u"scope",b"scope"]) -> None: ...
