# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Vertex(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    x = ... # type: builtin___int
    y = ... # type: builtin___int

    def __init__(self,
        *,
        x : typing___Optional[builtin___int] = None,
        y : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Vertex: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"x",u"y"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y"]) -> None: ...

class NormalizedVertex(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    x = ... # type: builtin___float
    y = ... # type: builtin___float

    def __init__(self,
        *,
        x : typing___Optional[builtin___float] = None,
        y : typing___Optional[builtin___float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> NormalizedVertex: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"x",u"y"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y"]) -> None: ...

class BoundingPoly(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def vertices(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Vertex]: ...

    @property
    def normalized_vertices(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[NormalizedVertex]: ...

    def __init__(self,
        *,
        vertices : typing___Optional[typing___Iterable[Vertex]] = None,
        normalized_vertices : typing___Optional[typing___Iterable[NormalizedVertex]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> BoundingPoly: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"normalized_vertices",u"vertices"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"normalized_vertices",b"normalized_vertices",u"vertices",b"vertices"]) -> None: ...

class Position(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    x = ... # type: builtin___float
    y = ... # type: builtin___float
    z = ... # type: builtin___float

    def __init__(self,
        *,
        x : typing___Optional[builtin___float] = None,
        y : typing___Optional[builtin___float] = None,
        z : typing___Optional[builtin___float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Position: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"x",u"y",u"z"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y",u"z",b"z"]) -> None: ...
