# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Color(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    red = ... # type: builtin___float
    green = ... # type: builtin___float
    blue = ... # type: builtin___float

    def __init__(self,
        *,
        red : typing___Optional[builtin___float] = None,
        green : typing___Optional[builtin___float] = None,
        blue : typing___Optional[builtin___float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Color: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"blue",u"green",u"red"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"blue",b"blue",u"green",b"green",u"red",b"red"]) -> None: ...
