# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from mlpiot.proto.google_timestamp_pb2 import (
    Timestamp as mlpiot___proto___google_timestamp_pb2___Timestamp,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Image(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    cycle_id = ... # type: builtin___int
    height = ... # type: builtin___int
    width = ... # type: builtin___int
    channels = ... # type: builtin___int
    url = ... # type: typing___Text
    data = ... # type: builtin___bytes

    @property
    def timestamp(self) -> mlpiot___proto___google_timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        cycle_id : typing___Optional[builtin___int] = None,
        timestamp : typing___Optional[mlpiot___proto___google_timestamp_pb2___Timestamp] = None,
        height : typing___Optional[builtin___int] = None,
        width : typing___Optional[builtin___int] = None,
        channels : typing___Optional[builtin___int] = None,
        url : typing___Optional[typing___Text] = None,
        data : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Image: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"timestamp"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channels",u"cycle_id",u"data",u"height",u"timestamp",u"url",u"width"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"timestamp",b"timestamp"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channels",b"channels",u"cycle_id",b"cycle_id",u"data",b"data",u"height",b"height",u"timestamp",b"timestamp",u"url",b"url",u"width",b"width"]) -> None: ...
