# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlpiot/proto/pipeline_overview.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlpiot.proto import action_execution_pb2 as mlpiot_dot_proto_dot_action__execution__pb2
from mlpiot.proto import event_pb2 as mlpiot_dot_proto_dot_event__pb2
from mlpiot.proto import event_extraction_pb2 as mlpiot_dot_proto_dot_event__extraction__pb2
from mlpiot.proto import google_timestamp_pb2 as mlpiot_dot_proto_dot_google__timestamp__pb2
from mlpiot.proto import image_pb2 as mlpiot_dot_proto_dot_image__pb2
from mlpiot.proto import scene_description_pb2 as mlpiot_dot_proto_dot_scene__description__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlpiot/proto/pipeline_overview.proto',
  package='mlpiot.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$mlpiot/proto/pipeline_overview.proto\x12\x0cmlpiot.proto\x1a#mlpiot/proto/action_execution.proto\x1a\x18mlpiot/proto/event.proto\x1a#mlpiot/proto/event_extraction.proto\x1a#mlpiot/proto/google_timestamp.proto\x1a\x18mlpiot/proto/image.proto\x1a$mlpiot/proto/scene_description.proto\"\xa0\x01\n\x1dVisionPipelineManagerMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x65vice_token\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65vice_hw_model\x18\x04 \x01(\t\x12 \n\x18\x64\x65vice_hw_model_icon_url\x18\x05 \x01(\t\x12\x0f\n\x07payload\x18\x06 \x01(\t\"\xa6\x03\n\x16VisionPipelineOverview\x12\x10\n\x08\x63ycle_id\x18\x01 \x01(\x03\x12*\n\ttimestamp\x18\x02 \x01(\x0b\x32\x17.mlpiot.proto.Timestamp\x12=\n\x08metadata\x18\x03 \x01(\x0b\x32+.mlpiot.proto.VisionPipelineManagerMetadata\x12(\n\x0binput_image\x18\x04 \x01(\x0b\x32\x13.mlpiot.proto.Image\x12\x39\n\x11scene_description\x18\x05 \x01(\x0b\x32\x1e.mlpiot.proto.SceneDescription\x12\x37\n\x10\x65xtracted_events\x18\x06 \x01(\x0b\x32\x1d.mlpiot.proto.ExtractedEvents\x12\x38\n\x11\x61\x63tion_executions\x18\x07 \x03(\x0b\x32\x1d.mlpiot.proto.ActionExecution\x12\x37\n\x1apipeline_management_events\x18\x08 \x03(\x0b\x32\x13.mlpiot.proto.Eventb\x06proto3'
  ,
  dependencies=[mlpiot_dot_proto_dot_action__execution__pb2.DESCRIPTOR,mlpiot_dot_proto_dot_event__pb2.DESCRIPTOR,mlpiot_dot_proto_dot_event__extraction__pb2.DESCRIPTOR,mlpiot_dot_proto_dot_google__timestamp__pb2.DESCRIPTOR,mlpiot_dot_proto_dot_image__pb2.DESCRIPTOR,mlpiot_dot_proto_dot_scene__description__pb2.DESCRIPTOR,])




_VISIONPIPELINEMANAGERMETADATA = _descriptor.Descriptor(
  name='VisionPipelineManagerMetadata',
  full_name='mlpiot.proto.VisionPipelineManagerMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mlpiot.proto.VisionPipelineManagerMetadata.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='mlpiot.proto.VisionPipelineManagerMetadata.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_token', full_name='mlpiot.proto.VisionPipelineManagerMetadata.device_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_hw_model', full_name='mlpiot.proto.VisionPipelineManagerMetadata.device_hw_model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_hw_model_icon_url', full_name='mlpiot.proto.VisionPipelineManagerMetadata.device_hw_model_icon_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='mlpiot.proto.VisionPipelineManagerMetadata.payload', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=416,
)


_VISIONPIPELINEOVERVIEW = _descriptor.Descriptor(
  name='VisionPipelineOverview',
  full_name='mlpiot.proto.VisionPipelineOverview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cycle_id', full_name='mlpiot.proto.VisionPipelineOverview.cycle_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mlpiot.proto.VisionPipelineOverview.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='mlpiot.proto.VisionPipelineOverview.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_image', full_name='mlpiot.proto.VisionPipelineOverview.input_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scene_description', full_name='mlpiot.proto.VisionPipelineOverview.scene_description', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extracted_events', full_name='mlpiot.proto.VisionPipelineOverview.extracted_events', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_executions', full_name='mlpiot.proto.VisionPipelineOverview.action_executions', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pipeline_management_events', full_name='mlpiot.proto.VisionPipelineOverview.pipeline_management_events', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=841,
)

_VISIONPIPELINEOVERVIEW.fields_by_name['timestamp'].message_type = mlpiot_dot_proto_dot_google__timestamp__pb2._TIMESTAMP
_VISIONPIPELINEOVERVIEW.fields_by_name['metadata'].message_type = _VISIONPIPELINEMANAGERMETADATA
_VISIONPIPELINEOVERVIEW.fields_by_name['input_image'].message_type = mlpiot_dot_proto_dot_image__pb2._IMAGE
_VISIONPIPELINEOVERVIEW.fields_by_name['scene_description'].message_type = mlpiot_dot_proto_dot_scene__description__pb2._SCENEDESCRIPTION
_VISIONPIPELINEOVERVIEW.fields_by_name['extracted_events'].message_type = mlpiot_dot_proto_dot_event__extraction__pb2._EXTRACTEDEVENTS
_VISIONPIPELINEOVERVIEW.fields_by_name['action_executions'].message_type = mlpiot_dot_proto_dot_action__execution__pb2._ACTIONEXECUTION
_VISIONPIPELINEOVERVIEW.fields_by_name['pipeline_management_events'].message_type = mlpiot_dot_proto_dot_event__pb2._EVENT
DESCRIPTOR.message_types_by_name['VisionPipelineManagerMetadata'] = _VISIONPIPELINEMANAGERMETADATA
DESCRIPTOR.message_types_by_name['VisionPipelineOverview'] = _VISIONPIPELINEOVERVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisionPipelineManagerMetadata = _reflection.GeneratedProtocolMessageType('VisionPipelineManagerMetadata', (_message.Message,), {
  'DESCRIPTOR' : _VISIONPIPELINEMANAGERMETADATA,
  '__module__' : 'mlpiot.proto.pipeline_overview_pb2'
  # @@protoc_insertion_point(class_scope:mlpiot.proto.VisionPipelineManagerMetadata)
  })
_sym_db.RegisterMessage(VisionPipelineManagerMetadata)

VisionPipelineOverview = _reflection.GeneratedProtocolMessageType('VisionPipelineOverview', (_message.Message,), {
  'DESCRIPTOR' : _VISIONPIPELINEOVERVIEW,
  '__module__' : 'mlpiot.proto.pipeline_overview_pb2'
  # @@protoc_insertion_point(class_scope:mlpiot.proto.VisionPipelineOverview)
  })
_sym_db.RegisterMessage(VisionPipelineOverview)


# @@protoc_insertion_point(module_scope)
