# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlpiot/proto/training.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlpiot/proto/training.proto',
  package='mlpiot.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bmlpiot/proto/training.proto\x12\x0cmlpiot.proto\"A\n\x0fTrainerMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0f\n\x07payload\x18\x03 \x01(\tb\x06proto3'
)




_TRAINERMETADATA = _descriptor.Descriptor(
  name='TrainerMetadata',
  full_name='mlpiot.proto.TrainerMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mlpiot.proto.TrainerMetadata.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='mlpiot.proto.TrainerMetadata.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='mlpiot.proto.TrainerMetadata.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['TrainerMetadata'] = _TRAINERMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainerMetadata = _reflection.GeneratedProtocolMessageType('TrainerMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TRAINERMETADATA,
  '__module__' : 'mlpiot.proto.training_pb2'
  # @@protoc_insertion_point(class_scope:mlpiot.proto.TrainerMetadata)
  })
_sym_db.RegisterMessage(TrainerMetadata)


# @@protoc_insertion_point(module_scope)
