# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from mlpiot.proto.action_execution_pb2 import (
    ActionExecution as mlpiot___proto___action_execution_pb2___ActionExecution,
)

from mlpiot.proto.event_extraction_pb2 import (
    EventExtraction as mlpiot___proto___event_extraction_pb2___EventExtraction,
)

from mlpiot.proto.event_pb2 import (
    Event as mlpiot___proto___event_pb2___Event,
)

from mlpiot.proto.google_timestamp_pb2 import (
    Timestamp as mlpiot___proto___google_timestamp_pb2___Timestamp,
)

from mlpiot.proto.image_pb2 import (
    Image as mlpiot___proto___image_pb2___Image,
)

from mlpiot.proto.scene_description_pb2 import (
    SceneDescription as mlpiot___proto___scene_description_pb2___SceneDescription,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class VisionPipelineManagerMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    version = ... # type: builtin___int
    device_token = ... # type: typing___Text
    device_hw_model = ... # type: typing___Text
    device_hw_model_icon_url = ... # type: typing___Text
    payload = ... # type: typing___Text

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        version : typing___Optional[builtin___int] = None,
        device_token : typing___Optional[typing___Text] = None,
        device_hw_model : typing___Optional[typing___Text] = None,
        device_hw_model_icon_url : typing___Optional[typing___Text] = None,
        payload : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> VisionPipelineManagerMetadata: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> VisionPipelineManagerMetadata: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"device_hw_model",b"device_hw_model",u"device_hw_model_icon_url",b"device_hw_model_icon_url",u"device_token",b"device_token",u"name",b"name",u"payload",b"payload",u"version",b"version"]) -> None: ...

class VisionPipelineData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: builtin___int

    @property
    def timestamp(self) -> mlpiot___proto___google_timestamp_pb2___Timestamp: ...

    @property
    def metadata(self) -> VisionPipelineManagerMetadata: ...

    @property
    def input_image(self) -> mlpiot___proto___image_pb2___Image: ...

    @property
    def scene_description(self) -> mlpiot___proto___scene_description_pb2___SceneDescription: ...

    @property
    def event_extraction(self) -> mlpiot___proto___event_extraction_pb2___EventExtraction: ...

    @property
    def action_executions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[mlpiot___proto___action_execution_pb2___ActionExecution]: ...

    @property
    def pipeline_management_events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[mlpiot___proto___event_pb2___Event]: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        timestamp : typing___Optional[mlpiot___proto___google_timestamp_pb2___Timestamp] = None,
        metadata : typing___Optional[VisionPipelineManagerMetadata] = None,
        input_image : typing___Optional[mlpiot___proto___image_pb2___Image] = None,
        scene_description : typing___Optional[mlpiot___proto___scene_description_pb2___SceneDescription] = None,
        event_extraction : typing___Optional[mlpiot___proto___event_extraction_pb2___EventExtraction] = None,
        action_executions : typing___Optional[typing___Iterable[mlpiot___proto___action_execution_pb2___ActionExecution]] = None,
        pipeline_management_events : typing___Optional[typing___Iterable[mlpiot___proto___event_pb2___Event]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> VisionPipelineData: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> VisionPipelineData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"event_extraction",b"event_extraction",u"input_image",b"input_image",u"metadata",b"metadata",u"scene_description",b"scene_description",u"timestamp",b"timestamp"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_executions",b"action_executions",u"event_extraction",b"event_extraction",u"id",b"id",u"input_image",b"input_image",u"metadata",b"metadata",u"pipeline_management_events",b"pipeline_management_events",u"scene_description",b"scene_description",u"timestamp",b"timestamp"]) -> None: ...
